card_metadata = {

    "major_arcana_fool.png": {"title": "The Fool", "upright": "New beginnings, spontaneity, free spirit.", "reversed": "Recklessness, fearlessness, risk-taking.", "zodiac": "Uranus", "element": "Air", "yes_no": "Yes"},
    "major_arcana_magician.png": {"title": "The Magician", "upright": "Manifestation, resourcefulness, power.", "reversed": "Manipulation, poor planning, untapped talents.", "zodiac": "Mercury", "element": "Air", "yes_no": "Yes"},
    "major_arcana_high_priestess.png": {"title": "The High Priestess", "upright": "Intuition, sacred knowledge, divine feminine.", "reversed": "Secrets, disconnected from intuition, withdrawal.", "zodiac": "Moon", "element": "Water", "yes_no": "Maybe"},
    "major_arcana_empress.png": {"title": "The Empress", "upright": "Femininity, beauty, nature, nurturing.", "reversed": "Creative block, dependence on others.", "zodiac": "Venus", "element": "Earth", "yes_no": "Yes"},
    "major_arcana_emperor.png": {"title": "The Emperor", "upright": "Authority, structure, fatherhood.", "reversed": "Domination, excessive control, rigidity.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "major_arcana_hierophant.png": {"title": "The Hierophant", "upright": "Spiritual wisdom, religious beliefs, conformity.", "reversed": "Personal beliefs, freedom, challenging the status quo.", "zodiac": "Taurus", "element": "Earth", "yes_no": "Maybe"},
    "major_arcana_lovers.png": {"title": "The Lovers", "upright": "Love, harmony, relationships, choices.", "reversed": "Disharmony, imbalance, misalignment of values.", "zodiac": "Gemini", "element": "Air", "yes_no": "Yes"},
    "major_arcana_chariot.png": {"title": "The Chariot", "upright": "Control, willpower, success, determination.", "reversed": "Lack of control, aggression, opposition.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "major_arcana_strength.png": {"title": "Strength", "upright": "Courage, persuasion, influence, compassion.", "reversed": "Self-doubt, weakness, insecurity.", "zodiac": "Leo", "element": "Fire", "yes_no": "Yes"},
    "major_arcana_hermit.png": {"title": "The Hermit", "upright": "Soul-searching, introspection, being alone.", "reversed": "Isolation, loneliness, withdrawal.", "zodiac": "Virgo", "element": "Earth", "yes_no": "Maybe"},
    "major_arcana_wheel.png": {"title": "The Wheel", "upright": "Good luck, karma, life cycles, destiny.", "reversed": "Bad luck, resistance to change, breaking cycles.", "zodiac": "Jupiter", "element": "Fire", "yes_no": "Yes"},
    "major_arcana_justice.png": {"title": "Justice", "upright": "Justice, fairness, truth, law.", "reversed": "Unfairness, lack of accountability, dishonesty.", "zodiac": "Libra", "element": "Air", "yes_no": "Maybe"},
    "major_arcana_hanged_man.png": {"title": "The Hanged Man", "upright": "Pause, surrender, letting go, new perspectives.", "reversed": "Delays, resistance, stalling.", "zodiac": "Neptune", "element": "Water", "yes_no": "No"},
    "major_arcana_death.png": {"title": "Death", "upright": "Endings, transformation, transition.", "reversed": "Resistance to change, personal transformation.", "zodiac": "Scorpio", "element": "Water", "yes_no": "No"},
    "major_arcana_temperance.png": {"title": "Temperance", "upright": "Balance, moderation, patience, purpose.", "reversed": "Imbalance, excess, self-healing.", "zodiac": "Sagittarius", "element": "Fire", "yes_no": "Yes"},
    "major_arcana_chains.png": {"title": "Chains", "upright": "Shadow self, attachment, addiction, restriction.", "reversed": "Releasing limiting beliefs, exploring dark thoughts.", "zodiac": "Capricorn", "element": "Earth", "yes_no": "No"},
    "major_arcana_tower.png": {"title": "The Tower", "upright": "Sudden change, upheaval, chaos, revelation.", "reversed": "Personal transformation, fear of change.", "zodiac": "Mars", "element": "Fire", "yes_no": "No"},
    "major_arcana_star.png": {"title": "The Star", "upright": "Hope, faith, purpose, renewal.", "reversed": "Lack of faith, despair, disconnection.", "zodiac": "Aquarius", "element": "Air", "yes_no": "Yes"},
    "major_arcana_moon.png": {"title": "The Moon", "upright": "Illusion, fear, anxiety, subconscious.", "reversed": "Release of fear, repressed emotion.", "zodiac": "Pisces", "element": "Water", "yes_no": "No"},
    "major_arcana_sun.png": {"title": "The Sun", "upright": "Positivity, fun, warmth, success.", "reversed": "Inner child, feeling down, overly optimistic.", "zodiac": "Sun", "element": "Fire", "yes_no": "Yes"},
    "major_arcana_judgement.png": {"title": "Judgement", "upright": "Judgement, rebirth, inner calling, absolution.", "reversed": "Self-doubt, inner critic, ignoring the call.", "zodiac": "Pluto", "element": "Fire", "yes_no": "Yes"},
    "major_arcana_world.png": {"title": "The World", "upright": "Completion, integration, accomplishment, travel.", "reversed": "Seeking personal closure, short-cuts, delays.", "zodiac": "Saturn", "element": "Earth", "yes_no": "Yes"},

    "minor_arcana_cups_1.png": {"title": "Ace of Cups", "upright": "Love and compassion.", "reversed": "Blocked emotions.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_2.png": {"title": "Two of Cups", "upright": "Partnership and unity.", "reversed": "Breakups or tension.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_3.png": {"title": "Three of Cups", "upright": "Friendship and celebration.", "reversed": "Overindulgence.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_4.png": {"title": "Four of Cups", "upright": "Apathy and contemplation.", "reversed": "Boredom, missed opportunity.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_5.png": {"title": "Five of Cups", "upright": "Loss and grief.", "reversed": "Dwelling on the negative.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_6.png": {"title": "Six of Cups", "upright": "Nostalgia and memories.", "reversed": "Stuck in the past.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_7.png": {"title": "Seven of Cups", "upright": "Choices and illusions.", "reversed": "Temptation, confusion.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_8.png": {"title": "Eight of Cups", "upright": "Withdrawal and seeking.", "reversed": "Avoidance, fear of change.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_9.png": {"title": "Nine of Cups", "upright": "Contentment and satisfaction.", "reversed": "Greed, dissatisfaction.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_10.png": {"title": "Ten of Cups", "upright": "Happiness and alignment.", "reversed": "Broken home, disconnection.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_page.png": {"title": "Page of Cups", "upright": "Creativity and curiosity.", "reversed": "Emotional immaturity, insecurity.", "zodiac": "Cancer", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_knight.png": {"title": "Knight of Cups", "upright": "Romance and charm.", "reversed": "Jealousy, moodiness.", "zodiac": "Pisces", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_queen.png": {"title": "Queen of Cups", "upright": "Compassion and calm.", "reversed": "Codependency, emotional insecurity.", "zodiac": "Scorpio", "element": "Water", "yes_no": "Yes"},
    "minor_arcana_cups_king.png": {"title": "King of Cups", "upright": "Emotional balance and control.", "reversed": "Manipulation, mood swings.", "zodiac": "Pisces", "element": "Water", "yes_no": "Yes"},

    "minor_arcana_wands_1.png": {"title": "Ace of Wands", "upright": "Inspiration and new opportunities.", "reversed": "Delays, lack of direction.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_2.png": {"title": "Two of Wands", "upright": "Planning and progress.", "reversed": "Lack of planning.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_3.png": {"title": "Three of Wands", "upright": "Expansion and foresight.", "reversed": "Obstacles, delays.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_4.png": {"title": "Four of Wands", "upright": "Celebration and harmony.", "reversed": "Lack of support.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_5.png": {"title": "Five of Wands", "upright": "Conflict and competition.", "reversed": "Avoidance, disagreement.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_6.png": {"title": "Six of Wands", "upright": "Victory and recognition.", "reversed": "Ego, hollow victory.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_7.png": {"title": "Seven of Wands", "upright": "Perseverance and defense.", "reversed": "Exhaustion, giving up.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_8.png": {"title": "Eight of Wands", "upright": "Speed and action.", "reversed": "Delays, frustration.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_9.png": {"title": "Nine of Wands", "upright": "Resilience and boundaries.", "reversed": "Wounded, on guard.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_10.png": {"title": "Ten of Wands", "upright": "Burden and responsibility.", "reversed": "Stress, overwhelmed.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_page.png": {"title": "Page of Wands", "upright": "Exploration and enthusiasm.", "reversed": "Lack of direction, procrastination.", "zodiac": "Sagittarius", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_knight.png": {"title": "Knight of Wands", "upright": "Energy and passion.", "reversed": "Impulsiveness, haste.", "zodiac": "Leo", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_queen.png": {"title": "Queen of Wands", "upright": "Courage and determination.", "reversed": "Jealousy, selfishness.", "zodiac": "Aries", "element": "Fire", "yes_no": "Yes"},
    "minor_arcana_wands_king.png": {"title": "King of Wands", "upright": "Leadership and vision.", "reversed": "Impulsiveness, overbearing.", "zodiac": "Leo", "element": "Fire", "yes_no": "Yes"},

    "minor_arcana_swords_1.png": {"title": "Ace of Swords", "upright": "Clarity and breakthroughs.", "reversed": "Confusion, misinformation.", "zodiac": "Gemini", "element": "Air", "yes_no": "Yes"},
    "minor_arcana_swords_2.png": {"title": "Two of Swords", "upright": "Indecision and choices.", "reversed": "Lies, stalemate.", "zodiac": "Libra", "element": "Air", "yes_no": "Maybe"},
    "minor_arcana_swords_3.png": {"title": "Three of Swords", "upright": "Heartbreak and sorrow.", "reversed": "Recovery, forgiveness.", "zodiac": "Libra", "element": "Air", "yes_no": "No"},
    "minor_arcana_swords_4.png": {"title": "Four of Swords", "upright": "Rest and recovery.", "reversed": "Burnout, stagnation.", "zodiac": "Libra", "element": "Air", "yes_no": "Yes"},
    "minor_arcana_swords_5.png": {"title": "Five of Swords", "upright": "Conflict and defeat.", "reversed": "Reconciliation, surrender.", "zodiac": "Aquarius", "element": "Air", "yes_no": "No"},
    "minor_arcana_swords_6.png": {"title": "Six of Swords", "upright": "Transition and change.", "reversed": "Resistance, unfinished business.", "zodiac": "Aquarius", "element": "Air", "yes_no": "Yes"},
    "minor_arcana_swords_7.png": {"title": "Seven of Swords", "upright": "Deception and strategy.", "reversed": "Coming clean, rethinking.", "zodiac": "Aquarius", "element": "Air", "yes_no": "No"},
    "minor_arcana_swords_8.png": {"title": "Eight of Swords", "upright": "Restriction and fear.", "reversed": "Release, new perspective.", "zodiac": "Gemini", "element": "Air", "yes_no": "No"},
    "minor_arcana_swords_9.png": {"title": "Nine of Swords", "upright": "Anxiety and despair.", "reversed": "Hope, reaching out.", "zodiac": "Gemini", "element": "Air", "yes_no": "No"},
    "minor_arcana_swords_10.png": {"title": "Ten of Swords", "upright": "Endings and betrayal.", "reversed": "Recovery, regeneration.", "zodiac": "Gemini", "element": "Air", "yes_no": "No"},
    "minor_arcana_swords_page.png": {"title": "Page of Swords", "upright": "Curiosity and vigilance.", "reversed": "Deception, all talk no action.", "zodiac": "Aquarius", "element": "Air", "yes_no": "Maybe"},
    "minor_arcana_swords_knight.png": {"title": "Knight of Swords", "upright": "Action and ambition.", "reversed": "Recklessness, disregard for consequences.", "zodiac": "Gemini", "element": "Air", "yes_no": "Yes"},
    "minor_arcana_swords_queen.png": {"title": "Queen of Swords", "upright": "Independence and perception.", "reversed": "Cold-hearted, cruel, bitterness.", "zodiac": "Libra", "element": "Air", "yes_no": "Maybe"},
    "minor_arcana_swords_king.png": {"title": "King of Swords", "upright": "Authority and truth.", "reversed": "Manipulation, misuse of power.", "zodiac": "Aquarius", "element": "Air", "yes_no": "Yes"},

    "minor_arcana_pentacles_1.png": {"title": "Ace of Pentacles", "upright": "Prosperity and new ventures.", "reversed": "Missed opportunity, instability.", "zodiac": "Taurus", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_2.png": {"title": "Two of Pentacles", "upright": "Balance and adaptability.", "reversed": "Financial disarray, juggling too much.", "zodiac": "Capricorn", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_3.png": {"title": "Three of Pentacles", "upright": "Collaboration and skill.", "reversed": "Disorganization, lack of teamwork.", "zodiac": "Capricorn", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_4.png": {"title": "Four of Pentacles", "upright": "Control and security.", "reversed": "Greed, insecurity.", "zodiac": "Capricorn", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_5.png": {"title": "Five of Pentacles", "upright": "Hardship and isolation.", "reversed": "Recovery, spiritual poverty.", "zodiac": "Taurus", "element": "Earth", "yes_no": "No"},
    "minor_arcana_pentacles_6.png": {"title": "Six of Pentacles", "upright": "Generosity and sharing.", "reversed": "Strings attached, debts.", "zodiac": "Taurus", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_7.png": {"title": "Seven of Pentacles", "upright": "Assessment and patience.", "reversed": "Impatience, wasted effort.", "zodiac": "Virgo", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_8.png": {"title": "Eight of Pentacles", "upright": "Mastery and diligence.", "reversed": "Perfectionism, lack of passion.", "zodiac": "Virgo", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_9.png": {"title": "Nine of Pentacles", "upright": "Abundance and self-sufficiency.", "reversed": "Overinvestment, superficial success.", "zodiac": "Virgo", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_10.png": {"title": "Ten of Pentacles", "upright": "Legacy and inheritance.", "reversed": "Financial failure, family burden.", "zodiac": "Virgo", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_page.png": {"title": "Page of Pentacles", "upright": "Ambition and desire.", "reversed": "Procrastination, lack of progress.", "zodiac": "Capricorn", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_knight.png": {"title": "Knight of Pentacles", "upright": "Efficiency and routine.", "reversed": "Laziness, obsessiveness.", "zodiac": "Virgo", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_queen.png": {"title": "Queen of Pentacles", "upright": "Nurturing and practicality.", "reversed": "Self-centeredness, jealousy.", "zodiac": "Taurus", "element": "Earth", "yes_no": "Yes"},
    "minor_arcana_pentacles_king.png": {"title": "King of Pentacles", "upright": "Wealth and discipline.", "reversed": "Stubbornness, materialism.", "zodiac": "Capricorn", "element": "Earth", "yes_no": "Yes"}
}